[package]
name = "reth-rlp"
version = "0.1.2"
edition = "2021"
license = "Apache-2.0"
description = "Fast RLP serialization library"
repository = "https://github.com/paradigmxyz/reth"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
auto_impl = "1"
bytes = { version = "1", default-features = false }
ethnum = { version = "1", default-features = false, optional = true }
smol_str = { version = "0.1", default-features = false, optional = true }
enr = { version = "0.7", default-features = false, optional = true }
rlp = { version = "0.5.2", default-features = false, optional = true }
ethereum-types = { version = "0.14", features = ["codec"], optional = true }
reth-rlp-derive = { version = "0.1", path = "./rlp-derive", optional = true }
revm-interpreter = { git = "https://github.com/bluealloy/revm", rev = "a05fb262d87c78ee52d400e6c0f4708d4c527f32", features = [] }

[dev-dependencies]
reth-rlp = { path = ".", package = "reth-rlp", features = [
    "derive",
    "std",
    "ethnum",
    "ethereum-types",
    "enr",
    "smol_str"
] }
criterion = "0.4.0"
hex-literal = "0.3"
rand = "0.8"
secp256k1 = { version = "0.24", features = [
    "rand-std",
] }

[features]
alloc = []
derive = ["reth-rlp-derive"]
std = ["alloc"]
enr = ["dep:enr", "dep:rlp", "enr/rust-secp256k1", "derive"]

[[bench]]
name = "bench"
harness = false
