[package]
name = "reth-discv4"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = """
Ethereum network discovery
"""

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-rlp = { path = "../../rlp", features = ["enr"] }
reth-rlp-derive = { path = "../../rlp/rlp-derive" }
reth-net-common = { path = "../common" }
reth-net-nat = { path = "../nat" }

# ethereum
discv5 = { git = "https://github.com/sigp/discv5" }
secp256k1 = { version = "0.24", features = [
    "global-context",
    "rand-std",
    "recovery",
] }
enr = { version = "0.7.0", default-features = false, features = [
    "rust-secp256k1",
] }

# async/futures
tokio = { version = "1", features = ["io-util", "net", "time"] }
tokio-stream = "0.1"

# misc
bytes = "1.2"
tracing = "0.1"
thiserror = "1.0"
hex = "0.4"
rand = { version = "0.8", optional = true }
generic-array = "0.14"
serde = "1.0"

[dev-dependencies]
rand = "0.8"
tokio = { version = "1", features = ["macros"] }
reth-tracing = { path = "../../tracing" }

[features]
test-utils = ["rand"]
