[package]
name = "reth-staged-sync"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Puts together all the Reth stages in a unified abstraction"

[package.metadata.cargo-udeps.ignore]
normal = [
    # Used for config loading
    "confy"
]

[dependencies]
# reth
reth-db = {path = "../../crates/storage/db", features = ["mdbx", "test-utils"] }
reth-discv4 = { path = "../../crates/net/discv4" }
reth-network-api = { path = "../../crates/net/network-api" }
reth-network = { path = "../../crates/net/network", features = ["serde"] }
reth-primitives = { path = "../../crates/primitives" }
reth-provider = { path = "../../crates/storage/provider", features = ["test-utils"] }
reth-net-nat = { path = "../../crates/net/nat" }
reth-interfaces = { path = "../interfaces", optional = true }

# io
serde = "1.0"
serde_json = "1.0.91"
confy = "0.5"

# misc
walkdir = "2.3.2"
eyre = "0.6.8"
shellexpand = "3.0.0"
tracing = "0.1.37"

# crypto
rand = { version = "0.8", optional = true }

# errors
thiserror = { version = "1", optional = true }

# enr
enr = { version = "0.7.0", features = ["serde", "rust-secp256k1"], optional = true }

# ethers
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false, optional = true }
ethers-providers = { git = "https://github.com/gakonst/ethers-rs", features = ["ws"], default-features = false, optional = true }
ethers-middleware = { git = "https://github.com/gakonst/ethers-rs", default-features = false, optional = true }
ethers-signers = { git = "https://github.com/gakonst/ethers-rs", default-features = false, optional = true }

# async / futures
async-trait = { version = "0.1", optional = true }
tokio = { version = "1", features = ["io-util", "net", "macros", "rt-multi-thread", "time"], optional = true }
tokio-test = { version = "0.4", optional = true }

# misc
tempfile = { version = "3.3", optional = true }
hex = { version = "0.4", optional = true }

[dev-dependencies]
# reth crates
reth-tracing = { path = "../tracing" }
reth-stages = { path = "../stages" }
reth-downloaders = { path = "../net/downloaders" }
reth-staged-sync = { path = ".", features = ["test-utils"] }

# async/futures
futures = "0.3"
tokio = { version = "1", features = ["io-util", "net", "macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1"

# crypto
secp256k1 = { version = "0.24", features = [
    "global-context",
    "rand-std",
    "recovery",
] }

[features]
test-utils = [
    "reth-network/test-utils",
    "reth-interfaces/test-utils",
    "reth-network/test-utils",
    "reth-provider/test-utils",
    "dep:enr",
    "dep:ethers-core",
    "dep:tempfile",
    "dep:thiserror",
    "dep:hex",
    "dep:rand",
    "dep:tokio",
    "dep:tokio-test",
    "dep:ethers-signers",
    "dep:ethers-providers",
    "dep:ethers-middleware",
    "dep:async-trait"
]
