[package]
name = "reth-ipc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = """
IPC support for reth
"""

[dependencies]

# async/net
futures = "0.3"
parity-tokio-ipc = "0.9.0"
tokio = { version = "1", features = ["net", "time", "rt-multi-thread"] }
tokio-util = { version = "0.7", features = ["codec"] }
async-trait = "0.1"
pin-project = "1.0"
tower = "0.4"

# misc
jsonrpsee = { version = "0.16", features = ["server", "client"] }
serde_json = "1.0"
tracing = "0.1.37"
bytes = "1.2.1"
thiserror = "1.0.37"

[dev-dependencies]
tracing-test = "0.2"

[features]
client = ["jsonrpsee/client", "jsonrpsee/async-client"]
