[package]
name = "reth-network-api"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Network interfaces"

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-eth-wire = { path = "../eth-wire" }

# io
serde = { version = "1.0", features = ["derive"] }

# misc
async-trait = "0.1"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["sync"] }
