[package]
name = "reth-transaction-pool"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = """
Transaction pool implementation
"""

[package.metadata.cargo-udeps.ignore]
normal = [
    # Used for diagrams in docs
    "aquamarine"
]

[dependencies]

# eth
reth-primitives = { path  = "../primitives" }

# async/futures
async-trait = "0.1"
futures-util = "0.3"
parking_lot = "0.12"
tokio = { version = "1", default-features = false, features = ["sync"] }

# rpc/metrics
metrics = "0.20.1"
reth-metrics-derive = { path = "../metrics/metrics-derive" }

# misc
aquamarine = "0.2.1" # docs
thiserror = "1.0"
tracing = "0.1"
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
fnv = "1.0.7"
bitflags = "1.3"

# ruint
# Using the uint! requires the crate to be imported
ruint = "1.7.0"

# testing
rand = { version = "0.8", optional = true }
paste = { version = "1.0", optional = true }

[dev-dependencies]
paste = "1.0"
rand = "0.8"


[features]
default = ["serde"]
serde = ["dep:serde"]
test-utils = ["rand", "paste", "serde"]
